### ISSUE TITLE
kali linux 

### ISSUE THREAD

**Issue by okotoko** [can-kat/cstealer#29]
in linux
after installed 
pip install -r requirements.txt
then
python builder,py  ...  eror:  python command not found

**Comment by can-kat** [comment]
Hello,

I never tested CStealer in Kali Linux machines so I can't support with your issue but can you try to re-install Python?

**Comment by CactusHamster** [comment]
The issue is you either don't have python installed, or python is installed as `python3` for compatibility (since python 2 will **not** work with python 3 code). Try `python3` instead of `python` first, and then try `sudo apt install python3` if neither python nor python3 are installed.
To my knowledge (I haven't used debian/kali for a little while) they both require `pip3`/`pip` to be installed with apt separately, if you need those.

**Comment by CactusHamster** [comment]
Due to #32 the script may not work on Kali Linux anyways without a slight modification.
