### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by lazpap11** [can-kat/cstealer#32]
When i run python builder.py this comes.im on termux

**Comment by CactusHamster** [comment]
`ctypes` is a Python module used for calling functions from shared or DLL libraries. According to the documentation, it appears that it only exports the property `windll` when on Windows. The file uses `ctypes.windll.kernel32` to set the title of the console prompt here:
https://github.com/can-kat/cstealer/blob/638a16f7f452e2845c9f3853e5d957730fa813e1/builder.py#L10
Because the module is used only once, and only provides an aesthetic effect, you could delete the function call altogether and it would be fine.
Maybe I'll work on a more permanent fix, or the owner could fix it with a commit.

**Comment by CactusHamster** [comment]
Reopening this issue as it is **not** completed.
